// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fdczNSWfwrvs2wEOmB_TL8lZ21TxWVE',
    appId: '1:643401413853:web:156df11f1cda1c2309d734',
    messagingSenderId: '643401413853',
    projectId: 'skit-bfb',
    authDomain: 'skit-bfb.firebaseapp.com',
    storageBucket: 'skit-bfb.firebasestorage.app',
    measurementId: 'G-JWG8DYGPKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQX5joJkI2FK2Vp7rwmL9bVmtx-4Pjnac',
    appId: '1:643401413853:android:aff767cdc17d4feb09d734',
    messagingSenderId: '643401413853',
    projectId: 'skit-bfb',
    storageBucket: 'skit-bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFpr5WglQ2AkTUb_UBJjZofhin65Dr594',
    appId: '1:643401413853:ios:22fab5d49235e47109d734',
    messagingSenderId: '643401413853',
    projectId: 'skit-bfb',
    storageBucket: 'skit-bfb.firebasestorage.app',
    iosBundleId: 'com.example.skitBfb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFpr5WglQ2AkTUb_UBJjZofhin65Dr594',
    appId: '1:643401413853:ios:22fab5d49235e47109d734',
    messagingSenderId: '643401413853',
    projectId: 'skit-bfb',
    storageBucket: 'skit-bfb.firebasestorage.app',
    iosBundleId: 'com.example.skitBfb',
  );
}
